### ISSUE TITLE
Checkbox does not capture click event in Firefox when a modifier key is pressed

### ISSUE THREAD

**Issue by greghuels** [isogon/styled-mdl#15]
Holding down alt/option, ctrl, or shift while clicking a checkbox does not toggle the checkbox.  Click and change events are not captured.

Tested on Firefox 54.0 (Mac)

**Comment by dweedon** [comment]
This is an issue with firefox, and there is not really a good workaround. You can probably implement something using keyup events instead of click or change to capture the input.

https://www.google.com/search?q=firefox+input+checkbox+modifier+key+click&rlz=1C5CHFA_enUS702US702&oq=firefox+input+checkbox+modifier+key+click&aqs=chrome..69i57.9535j0j1&sourceid=chrome&ie=UTF-8
